### ISSUE TITLE
Problème avec ngrok

### ISSUE THREAD

**Issue by thomas-vidal** [Grafikart/Docker-Compose-Local.dev#2]
Peux tu mettre a jour ton docker-compose pour intégrer Ngrok ?

**Comment by Grafikart** [comment]
J'utilise ngrok depuis la machine physique du coup je n'ai pas besoin d'avoir ngrok dans les composer. ce n'est pas ton cas ?

**Comment by thomas-vidal** [comment]
Ha j'ai cru qu'on pouvait l'utiliser de les composer désolé

**Comment by fayway** [comment]
Sachant que j'accède au site web dans la machine physique via http://192.168.99.100:8080, est ce qu'il suffit alors d'executer toujours dans la machine physique `ngrok http 192.168.99.100:8080` ?
